export const AUTH_MODULE_OPTIONS = 'AUTH_MODULE_OPTIONS';
export const AUTH_USER_SERIALIZATION_SERVICE = 'AUTH_USER_SERIALIZATION_SERVICE';
export const AUTH_USER_GOOGLE_MANAGER_SERVICE = 'AUTH_USER_GOOGLE_MANAGER_SERVICE';
export const JWT_TOKEN_GENERATOR_SERVICE = 'JWT_TOKEN_GENERATOR_SERVICE'
